# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('path', models.CharField(max_length=300, verbose_name='path')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(verbose_name='created')),
                ('started', models.DateTimeField(null=True, verbose_name='started')),
                ('finished', models.DateTimeField(null=True, verbose_name='finished')),
                ('log_level', models.SmallIntegerField(default=jobs.models.LogLevel(3), verbose_name='log_level')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Mesh',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
            ],
            bases=('jobs.job',),
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('job_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.Job')),
                ('max_correspondence', models.FloatField(verbose_name='max_correspondence')),
                ('max_iterations', models.IntegerField(verbose_name='max_iterations')),
                ('transformation_epsilon', models.FloatField(verbose_name='transformation_epsilon')),
                ('leaf_size', models.FloatField(verbose_name='leaf_size')),
            ],
            bases=('jobs.job',),
        ),
        migrations.AddField(
            model_name='file',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Job'),
        ),
    ]
