# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 08:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='job_id',
            new_name='job',
        ),
    ]
